sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.8.13/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install: ./create-dind-cluster.sh
